apiVersion: v1
kind: Service
metadata:
  name: http3-service
spec:
  type: ClusterIP
  selector:
    app: server
  ports:
    - name: http
      protocol: TCP
      port: 7000
      targetPort: 7000
    - name: udp
      protocol: UDP
      port: 7000
      targetPort: 7000

