apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: install
spec:
  components:
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      k8s:
        service:
          ports:
          - port: 15021
            targetPort: 15021
            name: status-port
          - port: 443
            targetPort: 8443
            name: https
          - port: 443
            targetPort: 8443
            name: http3
            protocol: UDP
  values:
    pilot:
      env:
        PILOT_ENABLE_QUIC_LISTENERS: true
