apiVersion: apps/v1
kind: Deployment
metadata:
  name: webtransport
  labels:
    app: webtransport
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webtransport
  template:
    metadata:
      labels:
        app: webtransport
    spec:
      containers:
      - name: webtransport
        image: webtransport:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 7005
          name: http3
          protocol: UDP
        - containerPort: 7005
          name: http3-tcp
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: webtransport-service
spec:
  type: NodePort
  selector:
    app: webtransport
  ports:
    - name: http3
      protocol: UDP
      port: 7005
      targetPort: 7005
    - name: http
      protocol: TCP
      port: 7005
      targetPort: 7005
